name: Title Validation on Pull Request (PR)

on:
    pull_request:
        branches:
            - main
            - canary
    pull_request_target:
        types:
            - opened
            - edited
            - synchronize
            - reopened

permissions:
    pull-requests: write

jobs:
    validate:
        name: Run Tests to Check Title on PR
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  types: |
                      build
                      chore
                      ci
                      cd
                      docs
                      feat
                      fix
                      perf
                      improvement
                      refactor
                      revert
                      style
                      test
                      conf
                      lib
                      prerelease
                      release
                  requireScope: false
                  subjectPattern: '^[a-z].+$'
                  subjectPatternError: |
                      The subject "{subject}" found in the PR title "{title}" does not comply with the specified pattern rules. Ensure that the title is written in lowercase.
